#
# *************************************************
# Copyright (c) 2019, Grant D. Miller
# License MIT: https://opensource.org/licenses/MIT
# **************************************************
#

version: 2.1
executorType: machine
jobs:
  static-analysis:
    docker:
      - image: newtmitch/sonar-scanner:3.2.0
    working_directory: ~/build
    steps:
      - checkout
      - save_cache:
          paths:
            - ~/.nuget
          key: csharp-cli-build-sonar-2-{{ checksum "src/cli.csproj" }}
      - run: |
         export TERM='xterm'
         dotnet --version
         java -version
         dotnet --list-runtimes
         export PATH="$PATH:/home/jenkins/.dotnet/tools"
         dotnet tool install --global dotnet-sonarscanner || true
         dotnet sonarscanner begin /n:${baseImageName} /key:${baseImageName} \
                /d:sonar.host.url=https://sonarcloud.io /d:sonar.login=$SONAR_AUTH_TOKEN \
                /d:sonar.exclusions=tests/**/*,doc/**/*,scripts/**/* \
                /d:sonar.branch.name=$CIRCLE_BRANCH \
                /d:sonar.test.inclusions=tests/**/* \
                /d:sonar.sourceEncoding=UTF-8 \
                /d:sonar.cs.opencover.reportsPaths=tests/coverage.opencover.xml
         dotnet build csharp-cli.sln
         dotnet test csharp-cli.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover || true
         dotnet sonarscanner end /d:sonar.login=$SONAR_AUTH_TOKEN
         
      - store_artifacts:
          path:  target
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine
    working_directory: ~/build
    
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build 

  license-headers:
    docker:
      - image: maven:3.5.3-jdk-8-alpine
    working_directory: ~/build
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: "-Xmx3200m "
    steps:
      - checkout
      - restore_cache:
          keys:
            - csharp-cli-build-lic-2-{{ checksum "pom-rat.xml" }}            
      - run: mvn dependency:go-offline -f pom-rat.xml -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - save_cache:
          paths:
            - ~/.m2
          key: csharp-cli-build-lic-2-{{ checksum "pom-rat.xml" }} -f pom-rat.xml
      - run: mvn clean -f pom-rat.xml license:check
  docker-build:
    docker:
      - image: docker:18.09.3
    working_directory: ~/build
    steps:
      - checkout
      - run: |
          DOCKER_TAG=branch-build 
          echo "running docker build script" && pwd && ./scripts/docker-build.sh $REPO $IMAGE_NAME $DOCKER_TAG
  docker-build-push:
    docker:
      - image: docker:18.09.3
    working_directory: ~/build
    steps:
      - checkout
      - run: |
          DOCKER_TAG=0.1
          echo "running docker build script" && pwd && ./scripts/docker-build-and-push.sh $REPO $IMAGE_NAME $DOCKER_TAG $DOCKER_REPO_HOST $DOCKER_USER $DOCKER_PASS
  fossa-scan:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine
    working_directory: ~/build
    steps:
      # Install Fossa
      - run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      - checkout
      - run: dotnet build
      - run: fossa init      
      - run: FOSSA_API_KEY=$FOSSA_API_KEY fossa analyze
workflows:
  version: 2
  build_test_and_push:
    jobs:
      - test
      - static-analysis
      - fossa-scan:
          filters:
            tags:
              only: /^v*.*.*/
            branches:
              only: master
      - license-headers
      - docker-build:
          requires:
          - test
          - static-analysis
          - license-headers
          filters:
            branches:
              ignore: master
      - docker-build-push:
          requires:
          - test
          - static-analysis
          - license-headers
          filters:
            tags:
              only: /^v*.*.*/
            branches:
              only: master

