#
# *************************************************
# Copyright (c) 2019, Grant D. Miller
# License MIT: https://opensource.org/licenses/MIT
# **************************************************
#

version: 2.1
jobs:
  static-analysis:
    docker:
      - image: newtmitch/sonar-scanner:alpine
    working_directory: ~/build-$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
    steps:
      - run: wget -O dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.2.6/dotnet-runtime-2.2.6-linux-musl-x64.tar.gz
      - run: echo "c4f45ab88ffda26b30c53b1db03e50fe0eaff92d6dd5daff05f4e019fc111405d016a787cadcb3a61df4e973d297a1f63ba2535f3802eff83b2e81b3c31cf0f9 dotnet.tar.gz" | sha512sum -c - 
      - run: mkdir -p /usr/share/dotnet \
              && tar -C /usr/share/dotnet -xzf dotnet.tar.gz \
              && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet \
              && rm dotnet.tar.gz
      - checkout
      - run: find .
      - run: |
         sonar-scanner \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.projectKey=$SONAR_PROJECT_KEY \
          -Dsonar.projectName=$SONAR_PROJECT_KEY \
          -Dsonar.organization=$SONAR_ORG \
          -Dsonar.login=$SONAR_AUTH_TOKEN \
          -Dsonar.branch.name=$CIRCLE_BRANCH \
          -Dsonar.sourceEncoding=UTF-8 \
          -Dsonar.externalIssuesReportPaths=target \
          -Dsonar.verbose=true \
          -Dsonar.sources=.       
      - store_artifacts:
          path:  target
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine
    working_directory: ~/build-$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM    
    steps:
      -  # Update, upgrade, then install  openssh for a clean checkout
      - run: apk update
      - run: apk upgrade
      - run: apk --no-cache add --update openssh
      - checkout
      - restore_cache:
          keys:
            - csharp-cli-test-1-{{ checksum "src/obj/project.assets.json" }}            
      - run: dotnet restore
      - save_cache:
          paths:
            - ~/.nuget
          key: csharp-cli-test-1-{{ checksum "src/obj/project.assets.json" }} -f pom-rat.xml
      
      - run: dotnet build
      - run: dotnet test --no-build 

  license-headers:
    docker:
      - image: maven:3.5.3-jdk-8-alpine
    working_directory: ~/build-$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: "-Xmx3200m "
    steps:
       # Update, upgrade, then install openssh for a clean checkout
      - run: apk update
      - run: apk upgrade
      - run: apk --no-cache add --update openssh
      - checkout
      - restore_cache:
          keys:
            - csharp-cli-build-lic-2-{{ checksum "pom-rat.xml" }}            
      - run: mvn dependency:go-offline -f pom-rat.xml -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - save_cache:
          paths:
            - ~/.m2
          key: csharp-cli-build-lic-2-{{ checksum "pom-rat.xml" }} -f pom-rat.xml
      - run: mvn clean -f pom-rat.xml license:check
  docker-build-push:
    docker:
      - image: docker:18.09.3
    working_directory: ~/build-$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # build and push Docker image to dockerhub.
      - run: |
          TAG=0.0.1
          docker build -t grantm/csharp-cli:$TAG .     
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push grantm/csharp-cli:$TAG
          # Tag and push latest
          docker tag grantm/csharp-cli:$TAG grantm/csharp-cli:latest
          docker push grantm/csharp-cli:latest
  fossa-scan:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine
    working_directory: ~/build-$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
    steps:
      # Update, upgrade, then install su, curl, bash and openssh
      - run: apk update
      - run: apk upgrade
      - run: set -ex && apk --no-cache add sudo
      - run: apk --no-cache add --update curl bash openssh
      # Install Fossa
      - run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | tac | tac | sudo bash
      # Install Maven
      - checkout
      - run: FOSSA_API_KEY=$FOSSA_API_KEY fossa init
      - run: FOSSA_API_KEY=$FOSSA_API_KEY fossa analyze
      # Note: The 'fossa test' command must be run after the analyze command has been run, as it is dependent on the previous scan.
      - run: FOSSA_API_KEY=$FOSSA_API_KEY fossa test
  vulnerability-test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine
    working_directory: ~/build-$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
    steps:
      - run: apk update
      - run: apk upgrade
      - run: set -ex && apk --no-cache add sudo
      - run: apk --no-cache add --update nodejs npm openssh
      - checkout 
      - run: dotnet restore
      - run: sudo npm_config_unsafe_perm=true npm install -g npm@latest
      - run: sudo npm_config_unsafe_perm=true npm install -g snyk@latest
      - run: sudo snyk auth $SNYK_TOKEN
      - run: sudo snyk test --file=csharp-cli.sln || true
workflows:
  version: 2
  build_test_and_push:
    jobs:
      - test
      - static-analysis
      - vulnerability-test
      - license-headers
      - fossa-scan:
          filters:
            tags:
              only: /^v*.*.*/
            branches:
              only: master      
      - docker-build-push:
          requires:
          - test
          - static-analysis
          - license-headers
          filters:
            tags:
              only: /^v*.*.*/
            branches:
              only: master

